
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - adcs.certmanager.csf.nokia.com
  resources:
  - adcsissuers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - adcs.certmanager.csf.nokia.com
  resources:
  - adcsissuers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - adcs.certmanager.csf.nokia.com
  resources:
  - adcsrequests
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - adcs.certmanager.csf.nokia.com
  resources:
  - adcsrequests/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - patch
- apiGroups:
  - adcs.certmanager.csf.nokia.com
  resources:
  - clusteradcsissuers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - adcs.certmanager.csf.nokia.com
  resources:
  - clusteradcsissuers/status
  verbs:
  - get
  - update
  - patch
